### ISSUE TITLE
Compatibility with map rotation

### ISSUE THREAD

**Issue by throwitaway99** [Danny-vD/Mods-LethalCompany-MonitorLabels#2]
There is a mod I use ([GeneralImprovements](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements)) that has a config feature called 'ShipMapCamDueNorth', which rotates the map camera to face north evenly as opposed to displaying everything at an angle. Unfortunately, the labels don't get properly rotated with the map, and so end up displaying upside down at an angle. Here is an example of how it appears.

![ShipMapCamDueNorth=true](https://github.com/Danny-vD/Mods-LethalCompany-MonitorLabels/assets/136512585/90e239e5-f191-439e-b0d2-fc85ce41e921)

And below is an example of how it appears with the default map orientation.

![ShipCamDueNorth=false](https://github.com/Danny-vD/Mods-LethalCompany-MonitorLabels/assets/136512585/252ceff9-f012-49b5-b606-48eb98daf015)

Would a fix for this be possible (always keeping the labels properly centered), or perhaps even require coordination with the developer of the [GeneralImprovements](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements) mod? Perhaps a map rotation feature natively in this mod (MonitorLabels) to alleviate the issue if nothing else?

**Comment by Danny-vD** [comment]
That's an interesting case that I hadn't thought of yet.

I'll be sure to fix it in version 1.2.1

Shouldn't take too long, I'll try to get it done tomorrow.

**Comment by Danny-vD** [comment]
It should work for all camera rotations now, even if the camera were to be rotated constantly (although I don't think there is any mod that does that at the moment).

While I was at it I also added config entries to manually set the offsets of the labels, which is why the version is `1.3.0` instead of `1.2.1`.

It will take a couple minutes for it to be updated on the thunderstore, but you can download the latest version manually from GitHub at https://github.com/Danny-vD/Mods-LethalCompany-MonitorLabels/releases/latest

Thanks again for pointing out this issue and let me know if something still does not work as intended.

**Comment by throwitaway99** [comment]
This particular issue has been solved, although another has been introduced. #3
